MVC/Controllers/EmployeesController.cs
using Application.DTOs;
using Application.IService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using Persistence.Entities;

namespace MVC.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IWebHostEnvironment _wepHostEnvironment;
        private readonly IEmployeeService _employeeService;

        public EmployeesController(IEmployeeService employeeService, IWebHostEnvironment wepHostEnvironment)
        {
            _employeeService = employeeService;
            _wepHostEnvironment = wepHostEnvironment;
        }

        public ActionResult Index()
        {
            var employees = _employeeService.GetAll().Select(employee => new EmployeeModel
            {
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                PhotoName = employee.ImageUrl,
                CreateAt = employee.CreateAt,
            }).ToList();

            var model = new IndexEmployeeViewModel()
            {
                Employees = employees,
                Employee = new EmployeeModel()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(IndexEmployeeViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    EmployeeDto employee = new EmployeeDto
                    {
                        FirstName = model.Employee.FirstName,
                        LastName = model.Employee.LastName,
                    };
                    if(model.Employee.Photo != null)
                    {
                    var fullPath = $"{_wepHostEnvironment.WebRootPath}\\Images\\{Path.GetFileName(model?.Employee.Photo?.FileName)}";
                    await using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        await model.Employee.Photo.CopyToAsync(stream);
                    }
                    employee.ImageUrl = $"/images/{Path.GetFileName(model.Employee.Photo.FileName)}";
                    }

                    _employeeService.Add(employee);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction(nameof(Index), new IndexEmployeeViewModel { Employee = model.Employee});
                }
            }
            catch
            {
                return View();
            }
        }

       
    }
}

MVC/Controllers/TasksController.cs
using Application.DTOs;
using Application.IService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using Persistence.Entities.Constant;

namespace MVC.Controllers
{
    public class TasksController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly ITaskEntityService _taskEntityService;
        public TasksController(IEmployeeService employeeService, ITaskEntityService taskEntityService)
        {
            _employeeService = employeeService;
            _taskEntityService = taskEntityService;
        }
        public ActionResult Index()
        {
            var employees = _employeeService.GetAll().Select(emp => new EmployeeModel { 
                ID = emp.ID, FirstName = emp.FirstName, LastName = emp.LastName 
            }).ToList();

            var status = Enum.GetValues(typeof(StatusTask)).Cast<StatusTask>().Select(sta => sta.ToString()).ToList();

            var task = _taskEntityService.GetAll().Select(task => new TaskModel
            {   
                ID = task.ID,
                Title = task.Title,
                Description = task.Description,
                ActualCost = task.ActualCost,
                TotalBudget = task.TotalBudget,
                StartDate = task.StartDate,
                EndDate = task.EndDate,
                ParentId = task.ParentId,
                Status = task.Status,
                Employees = task.Employees.Select(emp => new EmployeeModel { ID = emp.ID, PhotoName = emp.ImageUrl, FirstName = emp.FirstName, LastName = emp.LastName }).ToList(),
                Children = task.Children.Select(sub => new TaskModel
                {  
                    ID  = sub.ID,
                    Title = sub.Title,
                    Description = sub.Description,
                    ActualCost = sub.ActualCost,
                    TotalBudget = sub.TotalBudget,
                    StartDate = sub.StartDate,
                    EndDate = sub.EndDate,
                    ParentId = sub.ParentId,
                    Status = sub.Status,
                    Employees = sub.Employees.Select(emp => new EmployeeModel { ID = emp.ID, PhotoName = emp.ImageUrl, FirstName = emp.FirstName, LastName= emp.LastName }).ToList(),
                }).ToList(),
            }).ToList();
             
            var model = new IndexViewModel
            {
                Employees = employees,
                Status = status,
                Task = new TaskModel(),
                Tasks = task,
            };

            return View(model);
        }

        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IndexViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var employees = model.Task?.SelectedEmployees?.Select(id => new EmployeeDto { ID = id }).ToList();
                    var task = new TaskDto
                    {
                        Title = model.Task.Title,
                        Description = model.Task.Description,
                        ActualCost = model.Task.ActualCost,
                        TotalBudget = model.Task.TotalBudget,
                        StartDate = model.Task.StartDate,
                        EndDate = model.Task.EndDate,
                        ParentId = model.Task.ParentId,
                        Status = model.Task.Status,
                        Employees = employees,

                    };

                    _taskEntityService.Add(task);

                    return Json(new { success = true, message = "Sucssecful", status = 200 });
                }
                else
                {
                    return Json(new { success = false, message = "test error", status = 400 });
                }
            }
            catch
            {
                return  Json(new { success = false, message = "test error", status = 500 });
            }
        }

      
    }
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Task.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/filter-multi-select-main/dist/filter_multi_select.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
     <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
     <link rel="stylesheet" href="https://unpkg.com/tippy.js@@6/animations/scale.css"/>
     <!-- CSS only -->

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Task</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted position-absolute bottom-0 w-100">
        <div class="container">
            &copy; 2022 - Task - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/filter-multi-select-main/dist/filter-multi-select-bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/@@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@@6"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>